# **Cricket Prediction**

In [1]:
import pandas as pd
import pickle
import numpy as np

In [2]:
# !pip install pycaret

In [3]:
df = pickle.load(open('/content/dataset_level2.pkl','rb'))

In [4]:
df

# batting_team
# bowling team
# city
# current score
# ball left
# wickets left
# current rr
# last five

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,West Indies,India,0.1,0,0,Lauderhill,Central Broward Regional Park Stadium Turf Ground
1,2,West Indies,India,0.2,0,JD Campbell,Lauderhill,Central Broward Regional Park Stadium Turf Ground
2,2,West Indies,India,0.3,0,0,Lauderhill,Central Broward Regional Park Stadium Turf Ground
3,2,West Indies,India,0.4,1,0,Lauderhill,Central Broward Regional Park Stadium Turf Ground
4,2,West Indies,India,0.5,0,0,Lauderhill,Central Broward Regional Park Stadium Turf Ground
...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland,Eden Park
115310,964,Pakistan,New Zealand,19.3,0,Faheem Ashraf,Auckland,Eden Park
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland,Eden Park
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland,Eden Park
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland,Eden Park

In [5]:
df.isnull().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8545
venue                  0
dtype: int64

In [6]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        2966
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sharjah Cricket Stadium                     249
Sylhet International Cricket Stadium        128
Carrara Oval                                 64
Name: count, dtype: int64

In [7]:
cities = np.where(df['city'].isnull(),df['venue'].str.split().apply(lambda x:x[0]),df['city'])

In [8]:
df['city'] = cities

In [9]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [10]:
df.drop(columns=['venue'],inplace=True)

In [11]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,West Indies,India,0.1,0,0,Lauderhill
1,2,West Indies,India,0.2,0,JD Campbell,Lauderhill
2,2,West Indies,India,0.3,0,0,Lauderhill
3,2,West Indies,India,0.4,1,0,Lauderhill
4,2,West Indies,India,0.5,0,0,Lauderhill
...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland
115310,964,Pakistan,New Zealand,19.3,0,Faheem Ashraf,Auckland
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland

In [12]:
eligible_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()

In [13]:
df = df[df['city'].isin(eligible_cities)]

In [14]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,West Indies,India,0.1,0,0,Lauderhill
1,2,West Indies,India,0.2,0,JD Campbell,Lauderhill
2,2,West Indies,India,0.3,0,0,Lauderhill
3,2,West Indies,India,0.4,1,0,Lauderhill
4,2,West Indies,India,0.5,0,0,Lauderhill
...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland
115310,964,Pakistan,New Zealand,19.3,0,Faheem Ashraf,Auckland
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland

In [15]:
print(df['runs'].dtype)

int64

In [16]:
# df['current_score'] = df.groupby('match_id').cumsum()['runs']
df['current_score'] = df.groupby('match_id')['runs'].cumsum()

/tmp/ipython-input-16-3454559030.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [17]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
0,2,West Indies,India,0.1,0,0,Lauderhill,0
1,2,West Indies,India,0.2,0,JD Campbell,Lauderhill,0
2,2,West Indies,India,0.3,0,0,Lauderhill,0
3,2,West Indies,India,0.4,1,0,Lauderhill,1
4,2,West Indies,India,0.5,0,0,Lauderhill,1
...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland,149
115310,964,Pakistan,New Zealand,19.3,0,Faheem Ashraf,Auckland,149
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland,151
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland,152
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland,153

In [18]:
df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])
df

/tmp/ipython-input-18-2777558413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
/tmp/ipython-input-18-2777558413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no
0,2,West Indies,India,0.1,0,0,Lauderhill,0,0,1
1,2,West Indies,India,0.2,0,JD Campbell,Lauderhill,0,0,2
2,2,West Indies,India,0.3,0,0,Lauderhill,0,0,3
3,2,West Indies,India,0.4,1,0,Lauderhill,1,0,4
4,2,West Indies,India,0.5,0,0,Lauderhill,1,0,5
...,...,...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland,149,19,2
115310,964,Pakistan,New Zealand,19.3,0,Faheem Ashraf,Auckland,149,19,3
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland,151,19,4
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland,152,19,5
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland,153,19,6

In [19]:
df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')
df

/tmp/ipython-input-19-562775579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled
0,2,West Indies,India,0.1,0,0,Lauderhill,0,0,1,1
1,2,West Indies,India,0.2,0,JD Campbell,Lauderhill,0,0,2,2
2,2,West Indies,India,0.3,0,0,Lauderhill,0,0,3,3
3,2,West Indies,India,0.4,1,0,Lauderhill,1,0,4,4
4,2,West Indies,India,0.5,0,0,Lauderhill,1,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland,149,19,2,116
115310,964,Pakistan,New Zealand,19.3,0,Faheem Ashraf,Auckland,149,19,3,117
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland,151,19,4,118
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland,152,19,5,119
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland,153,19,6,120

In [20]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)
df

/tmp/ipython-input-20-2304996896.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = 120 - df['balls_bowled']
/tmp/ipython-input-20-2304996896.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
0,2,West Indies,India,0.1,0,0,Lauderhill,0,0,1,1,119
1,2,West Indies,India,0.2,0,JD Campbell,Lauderhill,0,0,2,2,118
2,2,West Indies,India,0.3,0,0,Lauderhill,0,0,3,3,117
3,2,West Indies,India,0.4,1,0,Lauderhill,1,0,4,4,116
4,2,West Indies,India,0.5,0,0,Lauderhill,1,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland,149,19,2,116,4
115310,964,Pakistan,New Zealand,19.3,0,Faheem Ashraf,Auckland,149,19,3,117,3
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland,151,19,4,118,2
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland,152,19,5,119,1
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland,153,19,6,120,0

In [21]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)

/tmp/ipython-input-21-739840433.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)

In [22]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
0,2,West Indies,India,0.1,0,0,Lauderhill,0,0,1,1,119
1,2,West Indies,India,0.2,0,1,Lauderhill,0,0,2,2,118
2,2,West Indies,India,0.3,0,0,Lauderhill,0,0,3,3,117
3,2,West Indies,India,0.4,1,0,Lauderhill,1,0,4,4,116
4,2,West Indies,India,0.5,0,0,Lauderhill,1,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland,149,19,2,116,4
115310,964,Pakistan,New Zealand,19.3,0,1,Auckland,149,19,3,117,3
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland,151,19,4,118,2
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland,152,19,5,119,1
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland,153,19,6,120,0

In [23]:
df['player_dismissed'] = df['player_dismissed'].astype('int')

/tmp/ipython-input-23-2510333364.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].astype('int')

In [24]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
0,2,West Indies,India,0.1,0,0,Lauderhill,0,0,1,1,119
1,2,West Indies,India,0.2,0,1,Lauderhill,0,0,2,2,118
2,2,West Indies,India,0.3,0,0,Lauderhill,0,0,3,3,117
3,2,West Indies,India,0.4,1,0,Lauderhill,1,0,4,4,116
4,2,West Indies,India,0.5,0,0,Lauderhill,1,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,0,Auckland,149,19,2,116,4
115310,964,Pakistan,New Zealand,19.3,0,1,Auckland,149,19,3,117,3
115311,964,Pakistan,New Zealand,19.4,2,0,Auckland,151,19,4,118,2
115312,964,Pakistan,New Zealand,19.5,1,0,Auckland,152,19,5,119,1
115313,964,Pakistan,New Zealand,19.6,1,0,Auckland,153,19,6,120,0

In [25]:
print(df['player_dismissed'].dtype)
print(df['player_dismissed'].unique())

int64
[0 1]

In [26]:
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()

/tmp/ipython-input-26-2543326779.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()

In [27]:
df['wickets_left'] = 10 - df['player_dismissed']

/tmp/ipython-input-27-526679617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wickets_left'] = 10 - df['player_dismissed']

In [28]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left
0,2,West Indies,India,0.1,0,0,Lauderhill,0,0,1,1,119,10
1,2,West Indies,India,0.2,0,1,Lauderhill,0,0,2,2,118,9
2,2,West Indies,India,0.3,0,1,Lauderhill,0,0,3,3,117,9
3,2,West Indies,India,0.4,1,1,Lauderhill,1,0,4,4,116,9
4,2,West Indies,India,0.5,0,1,Lauderhill,1,0,5,5,115,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,8,Auckland,149,19,2,116,4,2
115310,964,Pakistan,New Zealand,19.3,0,9,Auckland,149,19,3,117,3,1
115311,964,Pakistan,New Zealand,19.4,2,9,Auckland,151,19,4,118,2,1
115312,964,Pakistan,New Zealand,19.5,1,9,Auckland,152,19,5,119,1,1
115313,964,Pakistan,New Zealand,19.6,1,9,Auckland,153,19,6,120,0,1

In [29]:
df['crr'] = (df['current_score']*6)/df['balls_bowled']

/tmp/ipython-input-29-914577034.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crr'] = (df['current_score']*6)/df['balls_bowled']

In [30]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr
0,2,West Indies,India,0.1,0,0,Lauderhill,0,0,1,1,119,10,0.000000
1,2,West Indies,India,0.2,0,1,Lauderhill,0,0,2,2,118,9,0.000000
2,2,West Indies,India,0.3,0,1,Lauderhill,0,0,3,3,117,9,0.000000
3,2,West Indies,India,0.4,1,1,Lauderhill,1,0,4,4,116,9,1.500000
4,2,West Indies,India,0.5,0,1,Lauderhill,1,0,5,5,115,9,1.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115309,964,Pakistan,New Zealand,19.2,1,8,Auckland,149,19,2,116,4,2,7.706897
115310,964,Pakistan,New Zealand,19.3,0,9,Auckland,149,19,3,117,3,1,7.641026
115311,964,Pakistan,New Zealand,19.4,2,9,Auckland,151,19,4,118,2,1,7.677966
115312,964,Pakistan,New Zealand,19.5,1,9,Auckland,152,19,5,119,1,1,7.663866
115313,964,Pakistan,New Zealand,19.6,1,9,Auckland,153,19,6,120,0,1,7.650000

In [31]:
# groups = df.groupby('match_id')

# match_ids = df['match_id'].unique()
# last_five = []
# for id in match_ids:
#     last_five.extend(groups.get_group(id).rolling(window=30).sum()['runs'].values.tolist())



groups = df.groupby('match_id')

match_ids = df['match_id'].unique()
last_five = []
for id in match_ids:
    # Select the 'runs' column before applying rolling
    last_five.extend(groups.get_group(id)['runs'].rolling(window=30).sum().values.tolist())

In [32]:
df['last_five'] = last_five

/tmp/ipython-input-32-1595651733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_five'] = last_five

In [33]:
#df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','']]

In [34]:
final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')

In [35]:
final_df=final_df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]

In [36]:
final_df.dropna(inplace=True)

In [37]:
final_df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
balls_left       0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [38]:
final_df = final_df.sample(final_df.shape[0])

In [39]:
final_df.sample(2000)

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
9776,India,Pakistan,Johannesburg,40,88,9,7.500000,28.0,157
20028,New Zealand,Bangladesh,Mirpur,129,40,8,9.675000,51.0,204
13026,New Zealand,South Africa,Durban,72,62,8,7.448276,30.0,153
46874,New Zealand,West Indies,Mount Maunganui,231,4,8,11.948276,67.0,238
26723,New Zealand,South Africa,Hamilton,72,67,9,8.150943,37.0,173
...,...,...,...,...,...,...,...,...,...
12099,Pakistan,New Zealand,Auckland,168,3,2,8.615385,58.0,171
14499,Australia,India,Sydney,65,71,10,7.959184,40.0,164
7689,West Indies,Australia,St Lucia,56,70,7,6.720000,28.0,105
4379,Pakistan,Australia,Colombo,61,59,8,6.000000,33.0,149
39118,Australia,India,Sydney,69,75,9,9.200000,46.0,197

In [50]:
print(f"Total Cities: {final_df['city'].nunique()} → {final_df['city'].unique().tolist()}")

Total Cities: 35 → ['Pallekele', 'Bangalore', 'Centurion', 'Delhi', 'Durban', 'Mumbai', 'Barbados', 'Dubai', 'Southampton', 'Colombo', 'London', 'Lauderhill', 'Melbourne', 'Hamilton', 'Wellington', 'Manchester', 'Cape Town', 'Mount Maunganui', 'Lahore', 'Johannesburg', 'Mirpur', 'St Lucia', 'Nottingham', 'Auckland', 'Kolkata', 'Nagpur', 'Chittagong', 'Sydney', 'Trinidad', 'Christchurch', 'Abu Dhabi', 'Chandigarh', 'Adelaide', 'Cardiff', 'St Kitts']

In [51]:
print(f"Total Batting Teams: {final_df['batting_team'].nunique()} → {final_df['batting_team'].unique().tolist()}")

Total Batting Teams: 10 → ['New Zealand', 'India', 'Sri Lanka', 'South Africa', 'England', 'Pakistan', 'West Indies', 'Australia', 'Bangladesh', 'Afghanistan']

In [52]:
print(f"Total Bowling Teams: {final_df['bowling_team'].nunique()} → {final_df['bowling_team'].unique().tolist()}")

Total Bowling Teams: 10 → ['Bangladesh', 'England', 'Australia', 'South Africa', 'India', 'West Indies', 'New Zealand', 'Sri Lanka', 'Pakistan', 'Afghanistan']

In [40]:
X = final_df.drop(columns=['runs_x'])
y = final_df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [41]:
from pycaret.regression import *
import pandas as pd
import pickle

# Step 1: Combine features and target
df_model = pd.concat([X, y], axis=1)
df_model.rename(columns={'runs_x': 'target'}, inplace=True)

# Step 2: PyCaret Setup
setup(data=df_model,
      target='target',
      session_id=123,
      use_gpu=False,  # Set False if no GPU
      normalize=True,
      transformation=True,
      remove_multicollinearity=True,
      multicollinearity_threshold=0.9,
      verbose=False)

# Step 3: Compare and select top 5 models
top_models = compare_models(n_select=5,
                            sort='RMSE',
                            exclude=['tr', 'catboost'],
                            fold=5)

# Step 4: Save models + their individual metrics
model_info_list = []

for i, model in enumerate(top_models):
    model_name = str(model).split("(")[0]
    filename = f"{model_name}_model_{i}"

    # Save model
    save_model(model, filename)
    model_file = filename + ".pkl"

    # Predict and pull individual metrics
    predict_model(model)
    model_metrics = pull()

    model_info_list.append({
        "name": model_name,
        "filename": model_file,
        "metrics": model_metrics.to_dict()
    })

# Step 5: Save all metadata
with open("cricket_model_info_list.pkl", "wb") as f:
    pickle.dump(model_info_list, f)

# Step 6: Blend top models
blended = blend_models(estimator_list=top_models, fold=5)
save_model(blended, 'blended_model')

print("✅ Models trained, individually evaluated, and saved!")

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

Transformation Pipeline and Model Successfully Saved

Transformation Pipeline and Model Successfully Saved

Transformation Pipeline and Model Successfully Saved

Transformation Pipeline and Model Successfully Saved

Transformation Pipeline and Model Successfully Saved

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

Transformation Pipeline and Model Successfully Saved
✅ Models trained, individually evaluated, and saved!

In [48]:
import pandas as pd
from pycaret.regression import load_model, predict_model

# Sample test data
sample_data = pd.DataFrame({
    'batting_team': ['India', 'New Zealand', 'Australia'],
    'bowling_team': ['Pakistan', 'Bangladesh', 'India'],
    'city': ['Johannesburg', 'Mirpur', 'Sydney'],
    'current_score': [40, 129, 65],
    'balls_left': [88, 40, 71],
    'wickets_left': [9, 8, 10],
    'crr': [7.5, 9.675, 7.95],
    'last_five': [28.0, 51.0, 40.0]
})

# Load the saved model
model = load_model('blended_model')

# Predict
predictions = predict_model(model, data=sample_data)

# Check column names to confirm correct label
print("Columns in predictions DataFrame:", predictions.columns)

# Access correct column
sample_data['predicted_runs'] = predictions['prediction_label']

print(sample_data)

Transformation Pipeline and Model Successfully Loaded

Columns in predictions DataFrame: Index(['batting_team', 'bowling_team', 'city', 'current_score', 'balls_left',
       'wickets_left', 'crr', 'last_five', 'prediction_label'],
      dtype='object')
  batting_team bowling_team          city  current_score  balls_left  \
0        India     Pakistan  Johannesburg             40          88
1  New Zealand   Bangladesh        Mirpur            129          40
2    Australia        India        Sydney             65          71

   wickets_left    crr  last_five  predicted_runs
0             9  7.500       28.0      161.773192
1             8  9.675       51.0      203.133012
2            10  7.950       40.0      167.434973

In [ ]:
import pandas as pd
from pycaret.regression import load_model, predict_model

# Sample test data
sample_data = pd.DataFrame({
    'batting_team': ['India', 'New Zealand', 'Australia'],
    'bowling_team': ['Pakistan', 'Bangladesh', 'India'],
    'city': ['Johannesburg', 'Mirpur', 'Sydney'],
    'current_score': [40, 129, 65],
    'balls_left': [88, 40, 71],
    'wickets_left': [9, 8, 10],
    'crr': [7.5, 9.675, 7.95],
    'last_five': [28.0, 51.0, 40.0]
})

# Load the saved model
model = load_model('blended_model')

# Predict
predictions = predict_model(model, data=sample_data)

# Check column names to confirm correct label
print("Columns in predictions DataFrame:", predictions.columns)

# Access correct column
sample_data['predicted_runs'] = predictions['prediction_label']

print(sample_data)